version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - NEWS_API_KEY=Sd93cb7207b9f4ffea89bec6a6a9e6f66

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
