version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8085:8080"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}

  frontend:
    build: ./frontend
    ports:
      - "3005:80"
    depends_on:
      - backend

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8086:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
