services:
  db:
    image: mysql:8
    container_name: news-aggregator-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news-aggregator-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: news-aggregator-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
