version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      - NEWS_API_KEY=Sd93cb7207b9f4ffea89bec6a6a9e6f66
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/news_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_db
    ports:
      - "3306:3306"
