services:
  backend:
    build:
      context: ./backend   # points to backend folder
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
