version: '3.9'

services:
  backend:
    build: ./backend
    container_name: news-aggregator-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: news-aggregator-frontend
    ports:
      - "80:80"   # Nginx serves on port 80, not 3000
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: news-aggregator-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
