version: "3.9"

services:
  backend:
    build: ./backend   # Flask backend
    ports:
      - "5000:5000"
    environment:
      - NEWS_API_KEY=Sd93cb7207b9f4ffea89bec6a6a9e6f66

  frontend:
    build: ./frontend  # React or HTML frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
